controllers:
    resource:
        path: ../src/
        namespace: App
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: fr|en
    defaults:
        _locale: '%kernel.default_locale%'
