# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $mailerFrom: '%env(MAILER_FROM)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/*/Entity/'
            - '../src/*/Enum/'
